#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-bridge-macros"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition = "2024"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
heck = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
syn-mid = { workspace = true }

[dev-dependencies]
syn = { workspace = true, features = ["extra-traits"] }
