#
# Copyright (C) 2023 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-protocol-cross-version-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.4"
futures-util = "0.3.7"
log = "0.4"
rand = "0.9"
rand_v7 = { package = "rand", version = "0.7" }
rand_v8 = { package = "rand", version = "0.8" }
uuid = "1.0"

libsignal-protocol-current = { path = "..", package = "libsignal-protocol" }
libsignal-protocol-v70 = { git = "https://github.com/signalapp/libsignal", tag = "v0.70.0", package = "libsignal-protocol" }

# Prevent this crate from being included in the top-level workspace
[workspace]
members = ["."]
