#
# Copyright (C) 2020-2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-node"
version.workspace = true
authors.workspace = true
license.workspace = true
edition = "2024"

[lints]
workspace = true

[lib]
name = "signal_node"
crate-type = ["cdylib"]

[dependencies]
libsignal-bridge = { workspace = true, features = ["node", "signal-media"] }
libsignal-bridge-testing = { workspace = true, features = ["node", "signal-media"] }
libsignal-protocol = { workspace = true }

futures = { workspace = true }
log = { workspace = true }
log-panics = { workspace = true, features = ["with-backtrace"] }
minidump = { workspace = true }
minidump-processor = { workspace = true }
minidump-unwind = { workspace = true }
neon = { workspace = true, features = ["napi-6"] }

[build-dependencies]
# cmake 0.1.49 breaks no-toolchain Windows cross-compilation using Visual Studio
# https://github.com/rust-lang/cmake-rs/pull/158#issuecomment-1544695163
cmake = ">=0.1.22, <0.1.49"
